# This is a basic workflow to help you get started with Actions

name: Archive Users Unit

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  archive-users-unit:
    runs-on: ubuntu-latest
    steps:
    - name: Run archive users unit
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://maumt.se/chunks/db/archive_users_units.php'
        method: 'GET'
        preventFailureOnNoResponse: 'true'
