name: Deploy website on push

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request_target

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ upload.FTP_HOST }}
        username: ${{ upload.FTP_USER }}
        password: ${{ upload.FTP_PASS }}
