name: Deploy website on push

on:
  pull_request_target:
    types:
      - closed

jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    environment: upload
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp01.binero.se
        username: 244663_master
        password: ${{ secrets.ftp_password }}
